Implement nrm filename toml input
N64Recomp/N64Recomp pull request #111
Opened 2024-12-19 18:51 UTC by LittleCube-hax

Might suck but maybe it's cool?

2024-12-23 21:16 UTC, LittleCube-hax commented
i threw in renaming and RE

2024-12-23 21:30 UTC, Mr-Wiseguy requested changes
Great work on the renaming functionality and the mod toml changes, and RE mode is really interesting as well. I do think the name should be tweaked, since RE mode is a bit unclear (at first I thought it was related to the renaming functionality). A more descriptive name would be better to illustrate exactly what it does. Maybe "function_trace_mode"?

2024-12-23 21:30 UTC, Mr-Wiseguy commented on src/elf.cpp
> +            if (elf_config.has_entrypoint && (uint32_t) value == (uint32_t) elf_config.entrypoint_address && (type == ELFIO::STT_FUNC || type == ELFIO::STT_NOTYPE)) {
Why the changes here and below to include NOTYPE?

2024-12-23 21:30 UTC, Mr-Wiseguy commented on src/main.cpp
> -    bool dumping_context = false;
I'd prefer if this looked for an explicit flag, like `--dump-symbols`. The argc count change can stay, but the additional arguments should be checked against a flag list (which should just be this single flag for now).

2024-12-24 07:09 UTC, Mr-Wiseguy approved these changes

2024-12-24 07:10 UTC, merged